### ISSUE TITLE
Offset & Limit ipv Page 

### ISSUE THREAD

**Issue by rudiedirkx** [apiwise/postcodeapi#11]
Page size kunnen meegeven lijkt me zeer handig. Als je weet dat je ~ 90 resultaten gaat hebben, is 1 response voldoende, ipv 5 van 20.

Dan is Offset handiger dan Page, want dan kan je besluiten waar te beginnen, bijv `offset 40 limit 50`, na 2 pagina's van 20. Minder belangrijk dan Page size meegeven.

**Comment by joostfarla** [comment]
@rudiedirkx, kun je iets meer vertellen over de use case? We hebben de limiet namelijk bewust beperkt gehouden, omdat we niet in de hand willen werken dat men de hele database gaat scrapen. Als er goede use cases voor zijn kunnen we uiteraard kijken hoe we dit zo laagdrempelig mogelijk kunnen maken.

**Comment by rudiedirkx** [comment]
Dat is een goed punt. Ik zou niet weten waarom je heel veel resultaten terug zou krijgen, maar als het er 30 zijn, is het zonde om 2 requests te doen. Als het er 90 zijn, zonde om er 5 te doen, etc. Ik kan me voorstellen dat het limiet gelimiteerd wordt, maar 20 klinkt als weinig. Als jij niks kan bedenken dat meer dan 20 resultaten zou hebben, kan ik dat zeker niet =)

**Comment by dvh** [comment]
Op basis van V1 hebben we gemerkt dat het auto-completen van straatnaam + plaatsnaam op basis van postcode veruit de grootste use case is voor de Postcode API. Op [postcode niveau](https://htmlpreview.github.io/?https://raw.githubusercontent.com/apiwise/postcodeapi/master/docs/index.html#2822436bf819803aadee528cd5348881) krijg je alle adressen zonder paginering terug, dus daar zou je voor deze use case in 1 request het resultaat moeten kunnen krijgen. Op [adres niveau](https://htmlpreview.github.io/?https://raw.githubusercontent.com/apiwise/postcodeapi/master/docs/index.html#b47d7ff7dd264c3ece2b0c7a9c3ebbe9) kun je met filtering het aantal results beperken.
