### ISSUE TITLE
Adressen met meerdere purposes

### ISSUE THREAD

**Issue by joostfarla** [apiwise/postcodeapi#12]
Adressen kunnen meerdere "purposes" hebben. Dit attribuut zou dus een array moeten worden.

**Comment by dvh** [comment]
Navraag bij Kadaster leert ons dat dit een fout is in de brondata. Een verblijfsobject (adres) heeft altijd maar 1 huidige status en 1 huidig gebruiksdoel (purpose). Als er meerdere voorkomen dan gaat het om historische statussen/doelen die door de tijd heen zijn gewijzigd. Zie ook [deze SPARQL query](http://almere.pilod.nl/sparql?default-graph-uri=&query=prefix+bag%3A+%3Chttp%3A%2F%2Fbag.kadaster.nl%2Fdef%23%3E%0D%0Aselect+%3Fgegevenscombinatie+%3Fgrondslag+%3Fingangsdatum+%3Fgebruiksdoel%0D%0Awhere+%7B%0D%0A++++++++++++++++graph+%3Fgegevenscombinatie+%7B%0D%0A+++++++++++++++++++++++++++++++%3Chttp%3A%2F%2Fbag.kadaster.nl%2Fid%2Fverblijfsobject%2F0394010001003810%3E+bag%3Agebruiksdoel+%3Fgebruiksdoel.%0D%0A+++++++++++++++++++++++++++++++%3Fgegevenscombinatie+bag%3Agrondslag+%3Fgrondslag.%0D%0A+++++++++++++++++++++++++++++++%3Fgegevenscombinatie+bag%3Aingangsdatum+%3Fingangsdatum%0D%0A++++++++++++++++%7D%0D%0A%7D%0D%0A&should-sponge=&format=text%2Fhtml&timeout=0&debug=on) op het BAG endpoint. Er komen hier 4 resultaten verdeeld over 2 ingangsdatums terwijl dit er 2 moeten zijn. Voor nu gaan we dus uit van 1 purpose en 1 status en wachten we op een fix van de brondata om zeker te weten dat we de juiste teruggeven.
