### ISSUE TITLE
Wordt het HAL of JSON-LD?

### ISSUE THREAD

**Issue by kdekooter** [apiwise/postcodeapi#13]
In de readme wordt JSON-LD genoemd. In de docs staat echter HAL. Wat wordt het?

**Comment by dvh** [comment]
We willen een beperkte implementatie van HAL gebruiken in de normale `application/json` response om door de API te kunnen navigeren. JSON-LD moet terugkomen in de `application/ld+json` response.

**Comment by joostfarla** [comment]
We hebben nog onze bedenkingen bij het serveren van HAL, we kijken op dit moment naar de [JSON API spec](http://jsonapi.org/). Dit is de standaard in oa [Ember Data](guides.emberjs.com/v1.13.0/models/#toc_convention-over-configuration-with-json-api).

Zie voor de verschillen: http://jsonapi.org/faq/#why-not-use-the-hal-specification

Dit zou de default kunnen zijn als er geen `Accept` header is meegegeven in de request.

**Comment by kdekooter** [comment]
Dank!
