### ISSUE TITLE
Postcode + Huisnr

### ISSUE THREAD

**Issue by petericebear** [apiwise/postcodeapi#14]
Komt de postcode met huisnr (toevoeging) functie ook terug?

**Comment by dvh** [comment]
Jazeker, maar ons voorstel is om het op een iets andere manier te doen omdat is gebleken dat een postcode ook in meerdere straten kan vallen. De request kan gemaakt te worden op [postcode niveau](https://htmlpreview.github.io/?https://raw.githubusercontent.com/apiwise/postcodeapi/master/docs/index.html#2822436bf819803aadee528cd5348881) en in deze response vind je alle mogelijke adressen + huisnummers + toevoegingen. Een andere manier is om de request te maken op [adres collectie niveau](https://htmlpreview.github.io/?https://raw.githubusercontent.com/apiwise/postcodeapi/master/docs/index.html#b47d7ff7dd264c3ece2b0c7a9c3ebbe9) met de filterparameters `postcode` en `number`, dan krijg je alle fysieke adressen (dus op toevoeging/letter niveau) behorende bij deze combinatie.

**Comment by petericebear** [comment]
Die tweede optie lijkt mij denk ik de meeste snelle methode om tot een adres te komen. Gaat met name om postcode + huisnr invul opdrachten waarbij de straatnaam, plaats, provincie, lat en lng aangevuld kunnen worden. Dat scheelt de gebruiker invoeren en veel typefouten. blijft de API kosteloos benaderbaar in de toekomst?

**Comment by dvh** [comment]
We gaan beide opties ondersteunen. De API blijft zeker kosteloos benaderbaar.
