### ISSUE TITLE
Wijken en buurten

### ISSUE THREAD

**Issue by Roconda** [apiwise/postcodeapi#19]
Hallo,

In de kerncijfers excel van het CBS staan wijken en buurten. Is het mogelijk om deze data te importeren in de API? 

http://www.cbs.nl/nl-NL/menu/themas/dossiers/nederland-regionaal/cijfers/incidenteel/maatwerk/wijk-buurtstatistieken/kwb-recent/default.htm

**Comment by dvh** [comment]
Dank voor de suggestie! Dit lijkt mij meer iets voor de [PlaatsAPI](https://github.com/apiwise/plaatsapi) waar we momenteel ook mee bezig zijn. De meeste actuele Excel die ertussen staat bevat namelijk geen koppelingen om relaties te kunnen leggen met postcodes. Er worden straks wel koppelingen gelegd tussen de PostcodeAPI en de PlaatsAPI.

**Comment by dvh** [comment]
Verplaatst naar https://github.com/apiwise/plaatsapi/issues/2
