### ISSUE TITLE
Zoeken op P4 type postcodes

### ISSUE THREAD

**Issue by redelschaap** [apiwise/postcodeapi#26]
Zou handig zijn als er gezocht kon worden naar data die betrekking heeft op alleen de vier cijfers van een postcode, net zoals dat kon bij de oude API door `type=p4` toe te voegen aan de URL.

**Comment by joostfarla** [comment]
@redelschaap kun je meer vertellen over de use case?

**Comment by redelschaap** [comment]
Op één van onze websites kunnen bezoekers naar bedrijven zoeken op basis van postcode. Hoewel er in de zoekbalk op deze website om de postcode wordt gevraagd, zien we in de zoekdata dat veruit de meeste mensen alleen de cijfers van hun postcode invoeren. Het gaat dus vooral om cases waarbij de plaats (en evt. provincie) uit een P4 postcode moet worden gehaald.

De nieuwe API accepteert echter alleen P6 postcodes, wat inhoudt dat je er letters aan vast moet plakken. Het probleem is dan weer dat niet alle lettercombinaties in alle postcodegebieden bestaan.

**Comment by joostfarla** [comment]
OK helder :+1: Binnenkort introduceren we een `/postcodes` call, die exact hiervoor bedoeld is. Deze zal ook P4 gaan ondersteunen.

**Comment by redelschaap** [comment]
Super, ik kijk uit naar de update!

**Comment by tjveldhuizen** [comment]
Is er iets te zeggen over de termijn waarop versie 2.1 beschikbaar komt?

**Comment by dvh** [comment]
@tjveldhuizen ja, vandaag ;-)

**Comment by dvh** [comment]
Fixed.
