### ISSUE TITLE
Status query limit inzichtelijk maken

### ISSUE THREAD

**Issue by jschram** [apiwise/postcodeapi#27]
Als developer zou ik graag willen zien hoeveel queries ik met mijn huidige abonnement nog mag uitvoeren voor de lopende dag.

**Comment by joostfarla** [comment]
Idealiter zou iedere response custom HTTP headers bevatten met oa het resterende aantal API calls, maar helaas is dit momenteel nog niet mogelijk ivm een beperking van de AWS API Gateway.

We zitten er op dit moment aan te denken om voor de korte termijn een aparte API call te maken welke de belangrijkste gebruikersstatistieken teruggeeft incl het aantal resterende calls voor die dag. Zou je hiermee geholpen zijn?

**Comment by jschram** [comment]
Dat lijkt me al een stap in de goede richting! :+1: 
Op termijn is het inderdaad fijner als er bij elke call een credit-status wordt meegegeven.

**Comment by martijn80** [comment]
In response zou mooi zijn (luxe), maar aparte call/service is ook prima.

Ben benieuwd wat @jschram overigens met het resultaat zou willen doen. Dus wat als je merkt dat je door je dagelijkse quota heen bent?

**Comment by jschram** [comment]
@martijn80 Het zou bijvoorbeeld erg van pas komen bij de implementatie van load balancing tussen meerdere postcode providers.

**Comment by jorrit** [comment]
Als er een extra call komt zou het natuurlijk fijn zijn als die niet meetelt voor de limiet :)

**Comment by joostfarla** [comment]
Inmiddels heb ik begrepen dat AWS de benodigde ondersteuning biedt om aan iedere call deze dynamische headers mee te geven. Dit willen dus zsm gaan lanceren. Mocht een extra call toch benodigd/wenselijk zijn, dan zullen we er inderdaad voor zorgdragen dat deze niet ten koste gaat van de dagelijkse limiet!

**Comment by dvh** [comment]
Er komen 2 response headers bij: `X-RateLimit-Limit` met het limiet voor de client en `X-RateLimit-Remaining` met het aantal resterende calls voor die dag.

**Comment by dvh** [comment]
Fixed.
