### ISSUE TITLE
Bouwjaar uit BAG dataset

### ISSUE THREAD

**Issue by addoklopman** [apiwise/postcodeapi#28]
Het zou handig zijn meer data uit de BAG dataset via de API te kunnen opvragen zoals het bouwjaar van een pand.

**Comment by joostfarla** [comment]
We gaan uitzoeken of deze data in onze dataset zit. Indien ja, dan kunnen we die waarschijnlijk eenvoudig toevoegen.

**Comment by dvh** [comment]
Bouwjaar zit niet in onze dataset, is wel elders te krijgen. We gaan zoeken naar een manier om onze data hiermee te verrijken.

**Comment by dvh** [comment]
Brondata is gevonden en wordt opgenomen met volgende release.

**Comment by dvh** [comment]
Fixed.
