### ISSUE TITLE
Filters case-insensitive maken

### ISSUE THREAD

**Issue by SportconneXions** [apiwise/postcodeapi#31]
Ik wil graag de huidige 1.0 API implementatie omzetten naar 2.0.  Ik zie echter dat 2.0 geen simpele postcode API heeft die een stad + straat oplevert, klopt dat?  Wellicht omdat het mogelijk is dat een postcode kan worden toegekend aan meerdere straten?  Ik neem nu het eerste element van de array, maar dat kan misschien beter.  PS: Volgens mij is de API (postcode) nu case-sensitive, misschien handig voor in de documentatie?

**Comment by dvh** [comment]
Hoi @SportconneXions,

Bedankt voor je bericht. De reden dat het een array is, is inderdaad vanwege het feit dat er meerdere straten aan een postcode kunnen hangen. Meestal is er dus 1 resultaat, dus het eerste element van de array is inderdaad (meestal) de juiste manier.

De filter is inderdaad case-sensitive, maar wij vinden dat dit niet zo zou moeten zijn. Daarom hebben we de titel van dit issue aangepast en zullen we dit gaan veranderen in een volgende release.

**Comment by SportconneXions** [comment]
Bedankt voor de snelle reactie!

**Comment by jorrit** [comment]
Wellicht is het voor deze use-case handig om een `limit` parameter te introduceren omdat alleen het eerste resultaat gebruikt zal worden.

**Comment by SportconneXions** [comment]
@jorrit: Klopt, dat is ook wat beter voor de performance.

**Comment by dvh** [comment]
Dat ben ik niet geheel met jullie eens. In de meeste gevallen zal er maar 1 resultaat zijn (waardoor limit dus niet nodig is) en in een enkel geval zijn er meerdere resultaten (waarschijnlijk max 2). Als dit zo is dan is het onjuist om het eerste resultaat te gebruiken. In versie 1.0 van de Postcode API werkte het zo dat we altijd het eerste resultaat serveerden maar dat heeft tot veel klachten geleid van mensen die dus een verkeerde straatnaam bij een postcode kregen.

**Comment by jorrit** [comment]
Ik suggereer ook niet dat `limit` altijd 1 moet zijn, alleen dat het optioneel kan worden ingesteld. De gebruiker moet zich hiervan de consequenties realiseren, natuurlijk.

**Comment by joostfarla** [comment]
Binnenkort zal een nieuwe call geïntroduceerd worden, de "postcode" call. Deze stelt de ontwikkelaar in staat om op basis van enkel een postcode de plaats en straatna(a)m(en) op te vragen. Daarmee is bovenstaande opgelost denk ik?

**Comment by SportconneXions** [comment]
@Joost: Lijkt mij wel.  Ik gebruik de API idd met alleen de postcode (geen huisnummer).  De response kan dan een - in dit geval onnodig - groot aantal adressen bevatten.

**Comment by joostfarla** [comment]
@SportconneXions OK goed om te weten! Wat we proberen te doen is een helder onderscheid maken tussen "postcodes" en "adressen". Deze eerste bieden me nu (nog) niet aan, maar deze feature heeft momenteel onze hoogte prioriteit.

**Comment by dvh** [comment]
Postcode filter is nu case insensitive. De rest van dit issue wordt opgelost met issue #26, waarin we de `/postcodes` calls toevoegen.
