### ISSUE TITLE
Alleen gewenste attributen/dataset opvragen

### ISSUE THREAD

**Issue by DHFW** [apiwise/postcodeapi#32]
Het response object bevat nu veel data die ik niet nodig heb. Het zou handig zijn om gewenste attributen op te kunnen vragen (kleinere payload).

**Comment by jorrit** [comment]
Mee eens.

**Comment by dvh** [comment]
Ik ben erg benieuwd naar de use case en of je hinder ondervindt van de huidige payload. Met het introduceren van dergelijke features maken we het mijns inziens onnodig complex en wordt het bovendien lastiger om dingen te cachen, waardoor de payload wellicht kleiner wordt maar de response tijd hoger ;-)

**Comment by DHFW** [comment]
De use case is vrij simpel: adres validatie/verrijking. Ik zoek op postcode + huisnummer om de straatnaam, woonplaats, long+lat coördinaten op te halen. Vandaar dat de overige info voor mij niet nodig zijn... Een andere optie zou zijn een aparte api call hiervoor maken. Dus geen filter op attributen.

**Comment by dvh** [comment]
Dit wordt opgelost met de `/postcodes` call welke ook reeds beschreven staat in issue #26. De resource van één bepaalde postcode wordt dan `/postcodes/1234AB` met enkel gegevens over die postcode en een array van straten.
