### ISSUE TITLE
Testen met SoapUI

### ISSUE THREAD

**Issue by Criccle** [apiwise/postcodeapi#35]
Ik probeer de api aan te spreken via SoapUI om te testen of alles goed werkt en bruikbaar is, maar ik krijg de volgende foutmelding:

> Tue Feb 02 09:25:12 CET 2016:ERROR:Exception in request: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

Ik spreek dit adres aan: https://postcode-api.apiwise.nl/v2/addresses/?postcode.....(etcetc)
Tevens heb ik de header X-Api-Key toegevoegd.

Kan iemand mij vertellen wat ik verkeerd doe/wat ik aan moet passen?

**Comment by dvh** [comment]
SSLv3 wordt niet ondersteund omdat dit onveilig is (zie ook http://disablessl3.com/#faq). In plaats daarvan dien je TLSv1 te gebruiken. Hoogstwaarschijnlijk lost dat je probleem op!
