### ISSUE TITLE
overzicht gebruikte HTTP statuscodes?

### ISSUE THREAD

**Issue by woutkroon** [apiwise/postcodeapi#36]
De beschrijving van de API noemt (voor zover ik kan zien) alleen statuscode 200 voor een succesvolle call. Ik zou graag willen dat de overige statuscodes ook bescheven worden.

De usecase is het goed kunnen afhandelen van de API calls binnen de applicatie waarin dit wordt gedaan o.b.v. de verschillende statuscodes. Ik wil de eindgebruiker graag een nette/duidelijke foutmelding kunnen tonen o.b.v. de precieze reden waarom de call is gefaald.

Het is me overigens opgevallen dat de statuscode voor een call met ongeldige API key lijkt te zijn gewijzigd van 401 naar 403 (sinds vandaag). Klopt dat?

**Comment by dvh** [comment]
Hoi @woutkroon, dank voor je feedback. We zullen de documentatie updaten met alle statuscodes. Wat betreft jouw laatste vraag: dit was een bug en hebben we zojuist verholpen!

**Comment by woutkroon** [comment]
Hoi @dvh,
bedankt voor de snelle respons. Het was me opgevallen, omdat er een unittest was omgevallen die ik onlangs heb gemaakt. Daar zijn die dingen voor gelukkig :-).

**Comment by dvh** [comment]
Toegevoegd aan nieuwe API documentatie.
