### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by coenvl** [apiwise/postcodeapi#37]
Ik had een klein beetje verwacht hier al iets te kunnen vinden over dit probleem, ik kan me haast niet voorstellen dat niemand anders hier tegenaan is gelopen. Misschien doe ik ook gewoon wel iets doms, of zie ik iets heel simpels over het hoofd, dat zou natuurlijk ook kunnen.

Met het stukje voorbeeld vanaf de commandline lukt het mij om een request te doen, echter in javascript kom ik in de problemen. Ik probeer met een ingevoerde postcode automatisch het juiste adres te vinden, maar mijn browser (zowel Firefox 43.0.4 als Chrome 48.0.2564.97) begint te klagen op het moment dat ik een header "X-Api-Key" aan mijn request toevoeg, terwijl als ik hem niet toevoeg, ik uiteraard een 401 van de postcode-api krijg.

Volgens mij kan dit opgelost worden door aan de server kant iets te doen met de preflight request, en de X-Api-Key toe te voegen aan de toegestane request headers ([link](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Headers)).

**Comment by joostfarla** [comment]
@coenvl dank voor de melding! Met de release van vandaag is daar een foutje ingesloten. Ik heb het direct verholpen, dus je zou nu weer de juiste CORS headers moeten krijgen!

**Comment by coenvl** [comment]
Wow dat was snel. Hij doet het inderdaad weer.
