### ISSUE TITLE
All addresses by postcode, limit by number of results param?

### ISSUE THREAD

**Issue by henkmeulekamp** [apiwise/postcodeapi#38]
For the address by postcode api call:
` https://postcode-api.apiwise.nl/v2/addresses/?postcode=1234AB`

This resource could return many addresses found within the postcode. This request is for a use-case where we primarily want to have a only **city** and **street-name**.

Is there a way to limit the response to only the first found address or only the first address in each separate street name (for the special use cases where there are two street names in a postcode)?

It would be nice for example if there was a maxResults parameter:
` https://postcode-api.apiwise.nl/v2/addresses/?postcode=1234AB&maxResults=1`

Which would mean, give me max 1 results per street name.

**Comment by joostfarla** [comment]
@henkmeulekamp Thanks for reporting!

We are planning to introduce a new call, which accepts just a postcode. It will return the postcode attributes, like city and street (there can be multiple streets within one postcode though) and no addresses.

Example:
```
https://postcode-api.apiwise.nl/v2/postcodes/1234AB
```

It should be released soon!

**Comment by henkmeulekamp** [comment]
:+1:

**Comment by dvh** [comment]
Duplicates solution of #32
