### ISSUE TITLE
Is there a way to check how many requests are done/left in account?

### ISSUE THREAD

**Issue by henkmeulekamp** [apiwise/postcodeapi#39]
There is a daily limit on the amount of request available per membership level.

Is there any way to see stats on past requests or to see how many are left this day?

I've seen examples of other apis where there is some additional header information on response message containing the count of requests left for that day. 

For example twitter:
https://dev.twitter.com/rest/public/rate-limiting

> X-Rate-Limit-Limit: the rate limit ceiling for that given request
> X-Rate-Limit-Remaining: the number of requests left for the 15 minute window
> X-Rate-Limit-Reset: the remaining window before the rate limit resets in UTC epoch seconds
>  
> When an application exceeds the rate limit for a given API endpoint, the Twitter API will now return an HTTP 429 “Too Many Requests” response code.

**Comment by joostfarla** [comment]
It's on the roadmap and should be available soon!

Closing this in favor of https://github.com/apiwise/postcodeapi/issues/27.
