### ISSUE TITLE
Support voor P5 (1234A) schrappen

### ISSUE THREAD

**Issue by dvh** [apiwise/postcodeapi#4]
In versie 1.0 van de PostcodeAPI wordt er onderscheid gemaakt tussen P4 (1234), P5 (1234A) en P6 (1234AB). Volgens ons onderzoek is er eigenlijk alleen een praktisch verschil tussen het *postcodegebied* (P4) en een *postcode* (P6). P5 voegt niets toe, dus wat mij betreft kan ondersteuning hiervoor in versie 2.0 komen te vervallen.

**Comment by evertharmeling** [comment]
Eens, ik zie daar ook niet direct een usecase voor.
