### ISSUE TITLE
Registration Form including Creditcard does not have https

### ISSUE THREAD

**Issue by henkmeulekamp** [apiwise/postcodeapi#40]
Is this in the planning? I'm not sure we can enter cc details in a non-https form.

**Comment by dvh** [comment]
@henkmeulekamp the form submits to http*s*://postcode-api.apiwise.nl/v2/clients/signup ;-)

**Comment by jeroenlandheer** [comment]
@dvh This might be so... but a user should be able to verify that the form **comes from your site** in the first place. If the page isn't served over TLS, how the end user can verify that it isn't actually a malicious form?

**Comment by dvh** [comment]
Fixed.
