### ISSUE TITLE
A valid 'Api-Key' needs to be provided in the 'Headers' in order to use this API.

### ISSUE THREAD

**Issue by parmarkaushik15** [apiwise/postcodeapi#43]
I have received your API-KEY : - API KEY REMOVED -.

But it is not working give me this type of error message : A valid 'Api-Key' needs to be provided in the 'Headers' in order to use this API.

**Comment by dvh** [comment]
This is an error message of version 1.0 while the key is for version 2.0. You're connecting to http://api.postcodeapi.nu but this must be https://postcode-api.apiwise.nl.

**Comment by parmarkaushik15** [comment]
Heloo provide me full example in php so i can understand full after then i will purchase your api.

**Comment by dvh** [comment]
An example can be found here: http://www.postcodeapi.nu/docs

**Comment by parmarkaushik15** [comment]
i have tried this example. it is not give any type of output. i have tried 50 times. this example

**Comment by parmarkaushik15** [comment]
And not give any type of error response

**Comment by dvh** [comment]
No output probably means you try to connect using SSLv3. The new Postcode API only works with TLS.

**Comment by parmarkaushik15** [comment]
you can check this code

<?php
// De headers worden altijd meegestuurd als array
$headers = array();
$headers[] = 'X-Api-Key: fFaWW96Fl62poebPqFA8M2VwTfmocoJu5Y2XQguq';

// De URL naar de API call
$url = 'https://postcode-api.apiwise.nl/v2/addresses/?postcode=1234AB';

$curl = curl_init($url);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);

// De ruwe JSON response
$response = curl_exec($curl);

// Gebruik json_decode() om de response naar een PHP array te converteren
$data = json_decode($response);
  
  print_r($data);


curl_close($curl);

?>

**Comment by parmarkaushik15** [comment]
how can i use provide me help

**Comment by dvh** [comment]
http://blog.apiwise.nl/van-postcode-api-1-0-naar-2-0/

**Comment by parmarkaushik15** [comment]
provide me full example.

**Comment by dvh** [comment]
The code above and the code in the blogpost **are** full, working examples. You **must** use TLS instead of SSL: https://luxsci.com/blog/ssl-versus-tls-whats-the-difference.html

**Comment by parmarkaushik15** [comment]
just you provide me how to use tls instend of ssl

**Comment by dvh** [comment]
It depends on your server configuration, so I cannot help you with that. You could try this:

`curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);`

It will be less secure, but might work.

**Comment by parmarkaushik15** [comment]
Thanks to help me. your work is very good. I like it

**Comment by parmarkaushik15** [comment]
just give me idea how can i purchase your api...

Thanks 
Buddy

**Comment by dvh** [comment]
Please send me an e-mail: dimitri@apiwise.nl.
