### ISSUE TITLE
BAG id uit BAG dataset

### ISSUE THREAD

**Issue by allcaps** [apiwise/postcodeapi#44]
Kan het BAG id aan een response worden toegevoegd? Een request op BAG id zou ook tof zijn.

**Comment by joostfarla** [comment]
Het attribuut `id` in de response is de BAG id, ofwel de unieke identificatie van de [nummeraanduiding](http://bag.kadaster.nl/resource?subject=http%3A%2F%2Fbag.kadaster.nl%2Fid%2Fbegrip%2FNummeraanduiding&lang=nl). Ook bieden we de `/addresses/{id}` call, waarbij de `id` wederom staat voor de BAG ID.

Beantwoordt dat je vraag?

**Comment by allcaps** [comment]
Ja het beantwoord mijn vraag. Bedankt voor de snelle response.
