### ISSUE TITLE
Problem implementing postcodeapi 2.0

### ISSUE THREAD

**Issue by onouinou** [apiwise/postcodeapi#45]
We use postcodeapi 1.0 for long time and it works very fine we use a proxy to send the key and authentication. we try to change the url and key to new api 2.0 but it does not work
check bellow our working code of proxy page and the new code that does not work

working code for api 1.0

> 

`@using System.Net
@{
    string postcode = Request.QueryString["postalcode"];
	Response.ContentType = "test/json";
    if(!postcode.IsEmpty()){
        try
        {
            var request = HttpWebRequest.Create("http://api.postcodeapi.nu/" + postcode);
            request.Headers.Add("Api-Key", "dde2c0fe44ffc8b485d1be7e7ad17fd78153775e");
            HttpWebResponse response = (HttpWebResponse)request.GetResponse();
            StreamReader reader = new StreamReader(response.GetResponseStream());
            Response.Write(reader.ReadToEnd());
        }
        catch
        {
            Response.Write("{\"success\":false}");
        }
    }
    else
    {
        Response.Write("{\"success\":false}");
    }
}`

new code with changes and new key for api 2.0 (not working)
`@using System.Net
@{
    string postcode = Request.QueryString["postalcode"];
	Response.ContentType = "test/json";
    if(!postcode.IsEmpty()){
        try
        {
            var request = HttpWebRequest.Create("https://postcode-api.apiwise.nl/v2/addresses/?postcode=" + postcode);
            request.Headers.Add("Api-Key", "cLpdFtwYYu3s8sYZ4pdvI7MIM1wDtGIs3rtaCHfJ");
            HttpWebResponse response = (HttpWebResponse)request.GetResponse();
            StreamReader reader = new StreamReader(response.GetResponseStream());
            Response.Write(reader.ReadToEnd());
        }
        catch
        {
            Response.Write("{\"success\":false}");
        }
    }
    else
    {
        Response.Write("{\"success\":false}");
    }
}`

we have not changed anything in the js call to the api that is still the same
like:
`function postcodeToStreetAndSetInForm(){
			var postCode = $("#postcodeAutoFill").val();
				$.ajax({
				url: "/.global/shop/postcodeapi/proxy?postalcode="+ postCode,
					success: function (result){
					if (result.success) {
						$("#adres").val(result.resource.street);
						$("#plaats").val(result.resource.town);
					}
				}
			});
		}
`

please help if we need to change also the js or something else.

thank you in advance

**Comment by dvh** [comment]
V2 is completely different than V1. Please have a look at this post: http://blog.apiwise.nl/van-postcode-api-1-0-naar-2-0/ to migratie from V1 to V2

**Comment by onouinou** [comment]
Hi Dimitri 
Thank you for your very quick response and help. I can get thtrough authentication now and get the json back do you have any idea or maybe example how to parse the json using jquery
currently i am using this code to parse v1
`var postCode = $("#postcodeAutoFill").val();
				$.ajax({
				url: "/.global/shop/postcodeapi/proxy?postalcode="+ postCode,
					success: function (result){
					if (result.success) {
						$("#adres").val(result.resource.street);
						$("#plaats").val(result.resource.town);
					}
				}
			});`
please help with code snippet if possible
thank you very much in advance

**Comment by dvh** [comment]
http://www.postcodeapi.nu/docs/ contains the new document structure, so for example you need to access result._embedded.addresses... etc.
