### ISSUE TITLE
WSDL document zou handig zijn

### ISSUE THREAD

**Issue by RHAD1969** [apiwise/postcodeapi#47]
Het zou handig zijn als er een WSDL document zou zijn, zodat ik dit in Visual Studio zeer eenvoudig als web reference zou kunnen aanmaken

**Comment by dvh** [comment]
Zie https://swaggerhub.com/api/apiwise/postcode-api/2.0. Bij het pijltje rechtsboven kun je client libraries downloaden voor verschillende programmeertalen. WSDL is oorspronkelijk bedoeld voor SOAP services en aangezien dit een REST service is zou de Swagger spec met bijbehorende SDK's moeten voldoen.
