### ISSUE TITLE
Hoofdlettergevoelige header names

### ISSUE THREAD

**Issue by netiul** [apiwise/postcodeapi#49]
HTTP 1.1 specificeert dat de veld naam niet hoofdlettergevoelig is, maar als ik `x-api-key` (ipv. `X-Api-Key`) gebruik krijg ik een 401 access denied response terug. Dat zou niet moeten. Dit probleem kwam ik tegen na de release van 2.1.

**Comment by dvh** [comment]
@netiul klopt! Maar dat hebben we direct na de release verholpen als het goed is. Heb je nu nog steeds problemen?

**Comment by netiul** [comment]
Mooi, dan kan die gesloten worden.
