### ISSUE TITLE
Paginering GET /addresses lijkt niet te werken

### ISSUE THREAD

**Issue by joostdebruijn** [apiwise/postcodeapi#51]
Ik voer de volgende request uit op de API:
https://postcode-api.apiwise.nl/v2/addresses/?postcode=1183DE&number=500 

In het link-object onder "next" de volgende URL terug:
https://postcode-api.apiwise.nl/v2/addresses/?postcode=1183DE&number=500&from%5Bnumber%5D=500&from%5Bid%5D=0362200001001970&from%5Bpostcode%5D=1183DE. 

Echter, wanneer ik deze volg krijg ik een lege response terug. Dat verwacht ik niet aangezien er een next-link wordt gegeven en ik zeker weet dat de resultaten die ik terug krijg van de API nog niet volledig zijn, aangezien er meer dan twintig achtervoegsels zijn voor dit specifieke adres. Ook wanneer ik de API aanroep zonder de `number` parameter krijg ik een niet-werkende URL terug. Bij de API `GET /postcodes` werkt de paginering overigens wel naar behoren.

**Comment by joostfarla** [comment]
Good catch! Er zat een bug in de paginering in combinatie met de postcode filter. Deze is direct verholpen!

Fijne zondag nog gewenst! :)
