### ISSUE TITLE
Parameter voor huisnummertoevoeging

### ISSUE THREAD

**Issue by bronboek** [apiwise/postcodeapi#53]
Via de Postcode API kan momenteel alleen gezocht worden met de parameters 'postcode' en 'number'. Voor adresvalidatie zou het noodzakelijk zijn om ook 'huisnummertoevoeging' mee te kunnen nemen, bijvoorbeeld als parameter 'addition'. Deze lijkt overigens al wel teruggegeven te worden in de response, maar dan altijd met waarde NULL? Zowel in request als in response is deze parameter noodzakelijk.

**Comment by dvh** [comment]
De API ondersteunt alleen de filtering op huisnummer. Het vergelijken van de huisletter (`letter`) of huisnummer-toevoeging (`addition`) zal dus aan de applicatie-zijde moeten gebeuren. Wij hebben dat bewust niet geïmplementeerd, vanwege de verschillende representaties van toevoegingen (bijv. verschillende schrijfwijzen of het onderscheid tussen huisletter en toevoeging). Als je de API vraagt om een postcode/huisnummer combinatie krijg je alle adressen terug die voldoen aan deze criteria. Als hier huisletter of huisnummer-toevoegingen (of een combi van beiden) tussen zitten krijg je deze ook als aparte adressen terug. Wat je dus kan doen:

1. API call met postcode / huisnummer combi
2. Loop door alle resultaten heen en vergelijk de ingegeven toevoeging met de velden letter en/of addition. Dat is wel het punt waar het lastig wordt (en tevens de reden waarom wij het niet aanbieden), omdat je niet weet of een letter (bijv a) een huisletter of een toevoeging is. Je hebt bijv ook adressen zoals: 1A-30.

Overigens is het veld `addition` niet altijd null, enkel wanneer het niet bestaat. In de meeste gevallen zal dit dus in `letter` zitten :)

**Comment by bronboek** [comment]
Dank voor de reactie! Ik zie nu inderdaad dat in de resultaten de toevoeging in `letter` verstopt zit / kan zitten. Op zich kan ik dan inderdaad in een loop de gebruikersinvoer valideren tegen de (combinaties van) waarden van `number`, `addition` en `letter`. Ik ga proberen of ik er uit kom! :-)

**Comment by pieterdonkers** [comment]
Is dit niet op te lossen door gewoon een formaat te forceren waarin alleen nummers en letters mogen staan? Naar mijn mening is het een beetje onnodig om zo veel addressen terug te geven. Op zijn minst zou het filteren op de "Letter" alleen al iets toe voegen. Neem als voorbeeld 1033SC 23, hier worden 20 addressen terug gegeven.

**Comment by pieterdonkers** [comment]
Mocht je hier zelf geen zin in hebben te implementeren dan zou ik dit ook wel voor je kunnen doen.

**Comment by joostfarla** [comment]
De uitdaging met huisletters en huisnummer-toevoeging is met name dat hier allerlei exotische combinaties mogelijk zijn, bestaande uit cijfers, hoofd- en kleine letters, spaties, streepjes etc. Sommige adressen hebben zelfs zowel een huisletter als een huisnummer toevoeging, waarbij deze in de praktijk (op het fysieke huisnummer-bordje) vaak aan elkaar worden geplakt dmv diverse karakters (spaties, streepjes etc), terwijl deze in de basisregistratie als losse eigenschappen zijn opgenomen.

Naar mijn mening kunnen we niet van de gebruiker verwachten dat hij/zij:
* Het onderscheid kent tussen een huisletter en een huisnummer toevoeging
* De waardes exact invoert zoals deze in de basisregistratie bekend zijn. Zelfs als we "losjes" zouden matchen wordt dit lastig.

Wat we wel momenteel overwegen is om een versimpelde API call aan te bieden, waarbij je altijd maar 1 (of geen) adres terug krijgt, ook als er meerdere adressen zijn met verschillende letters/toevoegingen. We berekenen daarbij de geolocatie obv het gemiddelde van de betreffende adressen. Zou dat jouw probleem oplossen?

**Comment by pieterdonkers** [comment]
Ik heb mijn het al opgelost door inderdaad lokaal wat filtering toe te passen. Ook viel het me later op dat in de bovenstaande voorbeelden die ik noemde niet alle addressen aanwezig zijn. Ik weet niet of dit een bug is of dat jullie gewoon een maximaal aantal addressen terug geven. Ik heb even gekeken naar een paar addressen waar ik zeker van wist die bestonden maar niet werden terug gegeven.

**Comment by joostfarla** [comment]
De API geeft adressen gepagineerd per 20 terug. Als er meer dan 20 adressen zijn, dien je een extra request uit te voeren om de volgende 20 te bevragen. De URL voor de volgende pagina vind je in de response als next-link. In de JSON structuur is dat `_links` => `next` => `href`. Als er geen next-link in de response zit, betekent dit dat er niet meer resultaten zijn.

**Comment by pieterdonkers** [comment]
Ik had iets beter moeten kijken dus. Dom van me. Dankje voor de tip.
