### ISSUE TITLE
Nen5825 verschillend voor Address en Postcode Calls

### ISSUE THREAD

**Issue by janssenr** [apiwise/postcodeapi#54]
Waarom is de Nen5825 (straat) verschillend voor Address en Postcode Call.
Address Call geeft altijd 1 straat.
Postcode Call geeft een lijst met (mogelijk) meerdere straten.

In het voorbeeld op de website voor de postcode Call worden in de eigenschap "streets" wel meerdere straten terug gegeven, maar vervolgens in het Nen-resultaat staat er maar 1 straat. Moet dit dan wel een array van meerdere straten zijn?
       "streets": "[Binderskampweg, Kronenburgersingel]",
        "nen5825": {
          "streets": "[BINDERSKAMPWEG]",
          "postcode": "6545 CA"
        },

**Comment by dvh** [comment]
`streets` bij `/postcodes` moet een `array` zijn (in de docs staan onterecht quotes zie ik nu). Omdat het een voorbeeld betreft had er ook 'BLA' kunnen staan, maar het is inderdaad duidelijker als die straten overeen komen. Het klopt wel dat het per postcode meerdere straten kunnen zijn.

**Comment by janssenr** [comment]
Maar moet de Nen5825 bij de Address Call dan ook geen array van straten zijn? Want daar kan nu maar 1 straat staan.

**Comment by dvh** [comment]
Nee,Een adres heeft altijd maar 1 straat. Een postcode kan uit meerdere straten bestaan.

-----Oorspronkelijk bericht-----
Van: "Rob Janssen" <notifications@github.com>
Verzonden: ‎7-‎10-‎2016 12:28
Aan: "apiwise/postcodeapi" <postcodeapi@noreply.github.com>
CC: "Dimitri van Hees" <dimitri@apiwise.nl>; "Comment" <comment@noreply.github.com>
Onderwerp: Re: [apiwise/postcodeapi] Nen5825 verschillend voor Address enPostcode Calls (#54)

Maar moet de Nen5825 bij de Address Call dan ook geen array van straten zijn? Want daar kan nu maar 1 straat staan.
