### ISSUE TITLE
Geen resultaat voor bepaalde postcodes

### ISSUE THREAD

**Issue by ChadNCM** [apiwise/postcodeapi#55]
Als ik een lookup via de API doen voor 9406xm nummer 5 krijg ik geen resultaat (https://postcode-api.apiwise.nl/v2/addresses/?postcode=9406xm&number=5), terwijl het volgens https://www.postcode.nl/9406XM/5 degelijk bestaat? (Ik heb nog meer voorbeelden beschikbaar)

**Comment by dvh** [comment]
Interessant, dit is zo te zien een ligplaats/woonboot... Kun je nog wat andere voorbeelden posten?

**Comment by ChadNCM** [comment]
Ja zeker o.a.:
https://www.postcode.nl/9408AV/65
https://www.postcode.nl/9408AJ/21
https://www.postcode.nl/9408AW/2

**Comment by dvh** [comment]
Bij deze 3 krijg ik wel resultaat?

**Comment by janssenr** [comment]
Ik krijg nu bij 9406XM nummer 5 wel resultaat.
Of is er ondertussen iets aangepast?

@ChadNCM Ook over aan het gaan naar PostcodeApi omdat je voor PostcodeNl moet gaan betalen vanaf januari? ;)

**Comment by dvh** [comment]
@janssenr nee, er is niks aangepast. De eerste had ik zelf niet gechecked, maar ik krijg gewoon resultaat op de genoemde voorbeelden.

**Comment by janssenr** [comment]
9406XM 5
9408AV 65
9408AJ 21
9408AW 2
Ik krijg overal netjes resultaat. (1 adres)
@ChadNCM Wat voor (fout)melding krijg je dan? Heb je het wel goed geïmplementeerd?
Welke programmeertaal gebruik je?

**Comment by ChadNCM** [comment]
Dit is inderdaad heel vreemd, we krijgen nu voor alle 4 ook resultaten. We zijn nog aan het testen en houd het in de gaten. Dank in ieder geval voor de snelle response!

**Comment by dvh** [comment]
Ok, dan houden we dit issue nog even open mocht er nog iets geks zijn!

**Comment by cnroodbv** [comment]
Ik ben hier nog niet zo lang mee bezig dus misschien doe ik iets verkeerd maar ik loop tegen het zelfde issue aan b.v. 2333CS  nummer 30. Deze wordt wel gevonden op andere sites. Of 5216KT 360 of 2583CB 81 etc.

**Comment by janssenr** [comment]
2333CS 30 -> ik krijg 2 resultaten terug
5216KT 360 -> ik krijg 1 resultaat terug
2583CB 81 -> ik krijg 1 resultaat terug
@cnroodbv Wat voor (fout)melding krijg je dan? Heb je het wel goed geïmplementeerd?
Welke programmeertaal gebruik je?

**Comment by cnroodbv** [comment]
@janssennr Dan doe ik dus toch wat verkeerd :-) Ik ben net door mijn api calls heen voor vandaag dus ik kan het even niet meer proberen/testen. Ik gebruik php. Met het overgrote merendeel van de postcode's gaat het goed maar bij deze lijkt het alsof ik een leeg resultaat terug krijg. Ik ga het morgen weer proberen en laat van me horen. Bedankt voor je reactie in elk geval.

**Comment by janssenr** [comment]
@cnroodbv  Kun je de PHP code eens posten? Dan kan ik eens kijken of ik iets kan vinden.
En misschien ook het resultaat wat je dan krijgt.
https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo
Hiermee kun je ook de API aanroepen.

**Comment by cnroodbv** [comment]
@janssenr Ik ben er ondertussen achtergekomen dat alle drie de postcodes bij mijn run van vanmorgen vreemd genoeg **wel** zijn gevonden (na ~een week dagelijks proberen). Voor twee stuks was dit waarschijnlijk te wijten aan mijn code die niet goed om ging met speciale tekens  ('s-Hertogenbosch bv). Waarom 2333CS nu ook wel gevonden word, geen idee. Morgen kijken of ik er nog overhoud die niet gevonden worden...

**Comment by janssenr** [comment]
@cnroodbv Misschien omdat er bij 2333CS 2 resultaten terug komen?

**Comment by cnroodbv** [comment]
@janssenr Ik snap er zelf niets van maar in mijn batch van vandaag heb ik geen postcodes die niet gevonden kunnen worden. D.w.z. degene die nu niet gevonden worden zijn echt foute postcodes aan mijn kant. Nu heb ik wel van het weekend best veel veranderd aan mijn code, het bleek b.v. dat ik ook postcodes van postbussen probeerde, dat heeft geen zin heb ik ondertussen gezien. Wat ik nog moet opvangen zijn multi-page responses.
Vraagje voor wie het weet: Ik cache de resultaten lokaal en ga nu uit van een ttl van 3 maanden. Is dit een goede interval of worden de gegevens, veel, vaker of minder vaak bijgewerkt?

**Comment by dvh** [comment]
@cnroodbv de gegevens worden maandelijks geüpdate. Wat is eigenlijk precies je use-case dat je het zo lang cached?

**Comment by cnroodbv** [comment]
Usecase... Eigenlijk een persoonlijke uitdaging ;-) We hebben pas een overgang gehad van crm systeem. Buiten wat er dan al allemaal fout kan gaan bij het migreren zelf werd ook duidelijk hoeveel adressen er verkeerd zijn ingegeven. Meestal zijn dit typefouten. Ik wil nu proberen om de huidige gegevens te veriferen aan de hand van de postcode data. Aangezien mijn laatste programmeer ervaring richting de 10 jaar geleden is vormt dat een aardige uitdaging. Om niet te veel calls naar de server te maken (en als extra oefening) wil ik de gegevens cachen. Vanwaar de 3 maanden? Ik had geen idee hoe vaak deze gegevens worden aangepast/veranderen. Het leek me vrij statische data dus waarom korter cachen. Het is een leuk/uitdagend project voor me om ervaring met php/MySQL/ODBC op te doen.

**Comment by bekker004** [comment]
Ook ik ben de output voor bepaalde postcodes kwijt.
5211JE nummer 1 geeft correct Bastion oranje in 's-Hertogenbosch
5211JE nummer 57 geeft correct Zuidwal in 's-Hertogenbosch
5211JE nummer 10 geeft geen output i.p.v.  Zuidwal in 's-Hertogenbosch
5211JE nummer 58 geeft geen output i.p.v.  Zuidwal in 's-Hertogenbosch

**Comment by dvh** [comment]
@bekker004 Zuidwal 10 en 58 te 's-Hertogenbosch vallen in de postcode 5211JK ipv 5211JE.

**Comment by bekker004** [comment]
Beste Dimitri,
 
Sorry, dat is me nooit opgevallen en ik woon er toch al enkele jaren
Is een (niet te lange) straat.
Alle even en oneven nummers zitten aan dezelfde kant
m.u.v. nummer 1, dit is Bastion oranje (een historisch museumpje)
Nummer 2 bestaat niet 
Nummer 4-11 is dus 5211JK
Nummer 12-57 is dus 5211JE
Nummer 58 is weer 5211JK
 
Zal volgende keer ander testadres gebruiken J
 
Piet
 
Van: Dimitri van Hees [mailto:notifications@github.com] 
Verzonden: maandag 23 januari 2017 14:20
Aan: apiwise/postcodeapi
CC: Piet de Bekker; Mention
Onderwerp: Re: [apiwise/postcodeapi] Geen resultaat voor bepaalde postcodes (#55)
 
@bekker004 Zuidwal 10 en 58 te 's-Hertogenbosch vallen in de postcode 5211JK ipv 5211JE.
