### ISSUE TITLE
Foutieve opgave adres bij invoer postcode 2713 SZ

### ISSUE THREAD

**Issue by JacqLank** [apiwise/postcodeapi#56]
Deze postcode hoort bij Bijdorplaan 503. Door api wordt opgegeven Prinsestraat, dit is 2713 EN ??

**Comment by dvh** [comment]
Deze postcode geldt voor zowel Prinsestraat als Bijdorplaan en deze worden ook allebei teruggegeven. In combinatie met het huisnummer komt er wel Bijdorplaan uit.

**Comment by JacqLank** [comment]
Het gaat toch om de combinatie van postcode+letters?

**Comment by dvh** [comment]
Ik kan je niet helemaal volgen. Als je zoekt op adres (straat + huisnummer) gebruik je de address call:

`/addresses?postcode=2713sz&number=503` = Bijdorplaan

Als je zoekt op postcode (4 cijfers + 2 letters) gebruik je de postcode call:

`/postcodes/2713sz` = 2 straten, namelijk Bijdorplaan en Prinsestraat

**Comment by JacqLank** [comment]
De postcode api zit sinds deze week geimplementeerd in ons auto softwarepakket Driver als adres aanvulling. Dus je geeft eerst de postcode in, dan vult het pakket (via postcode api) de straatnaam in, waarna je zelf het huisnummer moet aanvullen. Vandaar dat er bij mij dus een verkeerde straat komt te staan.

Blijft wel dat Bijdorplaan 2713 SZ  heeft en Prinsestraat 2713 EN,  dus er hoort wel een andere opgave te volgen door de api

 

M.vr.gr.

 

Van: Dimitri van Hees [mailto:notifications@github.com] 
Verzonden: woensdag 23 november 2016 15:18
Aan: apiwise/postcodeapi
CC: JacqLank; Author
Onderwerp: Re: [apiwise/postcodeapi] Foutieve opgave adres bij invoer postcode 2713 SZ (#56)

 

Ik kan je niet helemaal volgen. Als je zoekt op adres (straat + huisnummer) gebruik je de address call:

/addresses?postcode=2713sz&number=503 = Bijdorplaan

Als je zoekt op postcode (4 cijfers + 2 letters) gebruik je de postcode call:

/postcodes/2713sz = 2 straten, namelijk Bijdorplaan en Prinsestraat

**Comment by dvh** [comment]
Een postcode kan meerdere straten bevatten, dat is bij 2713 SZ dan ook het geval. Prinsestraat 21 om precies te zijn, heeft postcode 2713 SZ. De implementatie in jullie pakket is dan dus ook niet juist: als je éérst een straatnaam terug wil krijgen alvorens het huisnummer zelf in te vullen dan zul je de gebruiker moeten vragen welke van de straten hij/zij bedoelt indien er meerdere straten onder één postcode vallen. Ik zou het persoonlijk dan ook anders oplossen, namelijk door de straatnaam en plaatsnaam pas in te vullen nadat zowel postcode en huisnummer zijn ingevuld.

**Comment by JacqLank** [comment]
Kan dat niet fout zijn dan?  Deze straten liggen veel te ver uit elkaar om dezelfde postcode te hebben!! Zie bijlage

 

Van: Dimitri van Hees [mailto:notifications@github.com] 
Verzonden: donderdag 24 november 2016 10:03
Aan: apiwise/postcodeapi
CC: JacqLank; Author
Onderwerp: Re: [apiwise/postcodeapi] Foutieve opgave adres bij invoer postcode 2713 SZ (#56)

 

Een postcode kan meerdere straten bevatten, dat is bij 2713 SZ dan ook het geval. Prinsestraat 21 om precies te zijn, heeft postcode 2713 SZ. De implementatie in jullie pakket is dan dus ook niet juist: als je éérst een straatnaam terug wil krijgen alvorens het huisnummer zelf in te vullen dan zul je de gebruiker moeten vragen welke van de straten hij/zij bedoelt indien er meerdere straten onder één postcode vallen. Ik zou het persoonlijk dan ook anders oplossen, namelijk door de straatnaam en plaatsnaam pas in te vullen nadat zowel postcode en huisnummer zijn ingevuld.

**Comment by dvh** [comment]
Bijlages werken niet in Github, maar dit is hoe het in de officiële brondata staat. En los van dit scenario kan het vaker voorkomen dat een postcode meerdere straten heeft, vandaar dat het een array is ;-)

**Comment by JacqLank** [comment]
Oke, ik geef het op. Bedankt voor de info

 

Van: Dimitri van Hees [mailto:notifications@github.com] 
Verzonden: donderdag 24 november 2016 11:15
Aan: apiwise/postcodeapi
CC: JacqLank; Author
Onderwerp: Re: [apiwise/postcodeapi] Foutieve opgave adres bij invoer postcode 2713 SZ (#56)

 

Bijlages werken niet in Github, maar dit is hoe het in de officiële brondata staat. En los van dit scenario kan het vaker voorkomen dat een postcode meerdere straten heeft, vandaar dat het een array is ;-)
