### ISSUE TITLE
Response array 'addresses' moet 'postcodes' zijn voor postcodes resource

### ISSUE THREAD

**Issue by BAPostma** [apiwise/postcodeapi#57]
Kleine fix voor de documentatie:
In documentatie staat bij de `/postcodes/` call dat `_embedded` een array genaamd `addresses` bevat.
In werkelijkheid moet dit voor deze call `postcodes` zijn.

**Comment by dvh** [comment]
+1

**Comment by dvh** [comment]
Fixed.
