### ISSUE TITLE
API geschikt voor JavaScript (Vue.js, Axios)

### ISSUE THREAD

**Issue by glenngijsberts** [apiwise/postcodeapi#59]
Is er een mogelijkheid tot api request vanuit JavaScript? Ik gebruik de plugin Axios samen met Vue.js  (javascript framework). Aan de hand van de documentatie kom ik niet veel verder met JavaScript, krijg geen data terug omdat hoogstwaarschijnlijk mijn niet geladen kan worden.

**Comment by joostfarla** [comment]
Afgaande op de Axios documentatie zou het volgende moeten werken:

```js
axios.get('https://postcode-api.apiwise.nl/v2/addresses/', {
  headers: {
    'X-Api-Key': 'REPLACE_WITH_YOUR_PERSONAL_KEY'
  },
  params: {
    postcode: '5038EA',
    number: 19
  }
}).then(function (response) {
  console.log(response._embedded.addresses);
}).catch(function (error) {
  console.error(error);
});
```

Een kleine waarschuwing bij het direct aanspreken van de API vanuit de browser. De API key wordt op deze manier blootgesteld aan de gebruiker en kan daardoor ook misbruikt worden door kwaadwillenden. We raden daarom altijd aan een eigen server-side script te implementeren die de daadwerkelijke API call uitvoert.

**Comment by glenngijsberts** [comment]
Is goed. Dank voor je snelle input.
