### ISSUE TITLE
NEN 5825 schrijfwijze toevoegen

### ISSUE THREAD

**Issue by JackPoint** [apiwise/postcodeapi#9]
Kunnen we in de API verschillende schrijfwijzen beschikbaar maken? Persoonlijk zou ik graag de schrijfwijze van NEN 5825 toegevoegd zien worden.

**Comment by joostfarla** [comment]
Goeie! We gaan onderzoeken of we deze data kunnen toevoegen.

**Comment by kdekooter** [comment]
Kunnen de relevante passages uit deze standaard aan het issue worden toegevoegd?

**Comment by JackPoint** [comment]
Het lijkt er op dat je die op https://www.nen.nl/NEN-Shop/Norm/NEN-58252002-nl.htm moet kopen. Ik weet niet of de dat dan hier zomaar neer mogen zetten.

**Comment by dvh** [comment]
@JackPoint wat is jouw use case? Als het gaat om de afkortingen van straatnamen (tot 24 karakters zodat het altijd in een venster envelop past, is blijkbaar de originele reden heb ik begrepen) dan zijn we daar mee bezig! Maar ik weet niet of het nog veel verder gaat dan dat en of dat relevant is?

**Comment by JackPoint** [comment]
Ik moet mijn klant data bij een extern systeem afleveren waarbij de data de NEN 5825 schrijfwijze moet zijn. Er zit dacht ik ook nog iets verschil en plaatsen en gemeenten wanneer je welke neemt. Ook de schrijfwijze van sommige plaatsen is iets anders, bijv met de provincie er bij. (EDE GLD)

**Comment by dvh** [comment]
We zijn er mee bezig, update: https://twitter.com/dvh/status/626109426777366529

**Comment by dvh** [comment]
Update: voor straten hebben we hem! Plaatsnamen nog niet...

**Comment by kdekooter** [comment]
Wat is het NEN formaat voor postcodes?

**Comment by dvh** [comment]
1234AB ?

**Comment by kdekooter** [comment]
Volgens mij moet er een spatie tussen: https://nl.wikipedia.org/wiki/Postcodes_in_Nederland (en deze informatie is gratis ;-)).

**Comment by dvh** [comment]
Yes, klopt!

**Comment by dvh** [comment]
Straat en postcode opgelost, plaatsnaam naar nieuw issue, #21
